### ISSUE TITLE
Autologon

### ISSUE THREAD

**Issue by dfranciscus** [StefanScherer/packer-windows#103]
Having a difficult time where autologon is disabled in the registry before post-processing. Or is it at all? I am a Packer noob and I have altered your windows_10.json a bit to work with MDT capturing the image. 

Problem I am having is that when I change the autounattend.xml to install updates that seems to stop autologon. If I disable installing updates in autounattend it works.

**Comment by StefanScherer** [comment]
The boxes normally have autologon. The final vagrant boxes also automatically log into the desktop session.
Maybe you have to add the autologon registry keys again.
But I can barely remember that I had a similar issue months ago. That's why the windows 10 answer file has additional commands to set registry keys https://github.com/StefanScherer/packer-windows/commit/8781254752da0f1911a6b5d5a2254bab73d650f4

**Comment by dfranciscus** [comment]
OK thanks. Driving me nuts. Ill try to set them again.
