### ISSUE TITLE
windows_2016_docker fails to build

### ISSUE THREAD

**Issue by jkodroff** [StefanScherer/packer-windows#11]
When I follow the instructions [here](https://github.com/StefanScherer/docker-windows-box), I get the following error:

```
    vmware-iso: SUCCESS: The scheduled task "InstallContainerImage" was successfully deleted.
    vmware-iso: Error response from daemon: no such id: windowsservercore:10.0.14300.1000
    vmware-iso: Error response from daemon: no such id: nanoserver:10.0.14300.1016
==> vmware-iso: Stopping virtual machine...
==> vmware-iso: Deleting output directory...
Build 'vmware-iso' errored: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
```

Any idea what the problem might be?  If there's any additional debugging info you need (or if I'm posting this to the wrong repo), please let me know.

Thanks!

**Comment by StefanScherer** [comment]
Looks like a problem tagging the images. As everything around Windows Container is in progress sometimes it's hard to have a working build.
You might try to comment out the [docker tag](https://github.com/StefanScherer/packer-windows/blob/149e036de7601fe4f076f731bde462ccad8d44cd/scripts/docker/install-docker.ps1#L98-L102) commands.

But perhaps the `Install-ContainerImage -Name ...` itself has failed and no image is installed. I've checked the available container images with

```
C:\Windows\system32> Find-ContainerImage

Name                           Version          Source           Summary
----                           -------          ------           -------
NanoServer                     10.0.14300.1016  ContainerImag... Container OS Image of Windows Server 20...
WindowsServerCore              10.0.14300.1000  ContainerImag... Container OS Image of Windows Server 20...
```
 
and the version numbers are still the same as in the `install-docker.ps1` script.

So you can add a `docker images` after the `Start-Service docker` in the `install-docker.ps1` script to see which images are available.

**Comment by StefanScherer** [comment]
@jkodroff Please pull my latest changes from GitHub and retry. I have just removed the scheduled task as we now can use `docker pull` to download the windows os base images.

The important change is in this script:
https://github.com/StefanScherer/packer-windows/blob/my/scripts/docker/install-docker.ps1

**Comment by colinng** [comment]
When I try to build a container for Windows 2016 using your [packer-windows](https://github.com/StefanScherer/packer-windows) repo and adopting what I can from https://stefanscherer.github.io/setup-local-windows-2016-tp5-docker-vm/
for VirtualBox, it seems to freeze "Waiting for WinRM to become available...". The container is built - I can see the Windows 2016 desktop, but I don't know how to package that container up because the packer process doesn't complete and generate a .box file. 

I've tried removing the Windows Update steps, and have repeated the process a few times, but I can't figure out what I am doing wrong. 

Would you kindly help, or point me to instructions? 

-----

$ packer build --only virtualbox-iso ./windows_2016.json
virtualbox-iso output will be in this color.

==> virtualbox-iso: Downloading or copying ISO
    virtualbox-iso: Downloading or copying: http://care.dlservice.microsoft.com/dl/download/1/6/F/16FA20E6-4662-482A-920B-1A45CF5AAE3C/14393.0.160715-1616.RS1_RELEASE_SERVER_EVAL_X64FRE_EN-US.ISO
==> virtualbox-iso: Creating floppy disk...
    virtualbox-iso: Copying: ./answer_files/2016/Autounattend.xml
    virtualbox-iso: Copying: ./floppy/WindowsPowershell.lnk
    virtualbox-iso: Copying: ./floppy/PinTo10.exe
    virtualbox-iso: Copying: ./scripts/disable-winrm.ps1
    virtualbox-iso: Copying: ./scripts/enable-winrm.ps1
    virtualbox-iso: Copying: ./scripts/microsoft-updates.bat
    virtualbox-iso: Copying: ./scripts/oracle-cert.cer
==> virtualbox-iso: Creating virtual machine...
==> virtualbox-iso: Creating hard drive...
==> virtualbox-iso: Attaching floppy disk...
==> virtualbox-iso: Creating forwarded port mapping for communicator (SSH, WinRM, etc) (host port 3559)
==> virtualbox-iso: Executing custom VBoxManage commands...
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1475143619 --memory 2048
    virtualbox-iso: Executing: modifyvm packer-virtualbox-iso-1475143619 --cpus 2
==> virtualbox-iso: Starting the virtual machine...
==> virtualbox-iso: Waiting 2m0s for boot...
==> virtualbox-iso: Typing the boot command...
==> virtualbox-iso: Waiting for WinRM to become available...

**Comment by StefanScherer** [comment]
Windows Updates are mandatory, as discussed in https://github.com/Microsoft/Virtualization-Documentation/issues/358#issuecomment-249879435

What do you see at the desktop of the VM? It should pop up a shell window that shows the windows update script downloading and installing updates. It may reboot until it is finished. After the windows updates it opens the WinRM port and packer will do the next steps.

Another idea: As you are trying to create a virtualbox VM, you may try this Atlas box https://atlas.hashicorp.com/mwrock/boxes/Windows2016 and then installing Docker in a Vagrant provision script.

**Comment by colinng** [comment]
Thanks Stefan for replying! When I run it with the updates, it does indeed show a shell window and installs the updates, rebooting when done. I don't think it does the next part which is opening a WinRM port. I'll try again and see what happened.

**Comment by colinng** [comment]
Thanks for suggesting the Atlas box, as that worked. I'll see if I can figure out how to get WinRM working on packer-windows for VirtualBox as I do like being able to build a container from scratch.

**Comment by StefanScherer** [comment]
After rebuilding several times today without an issue I'll close this one.
