### ISSUE TITLE
Hyperv provider for windows_2019 

### ISSUE THREAD

**Issue by hegyre** [StefanScherer/packer-windows#332]
Hello,

Can you please put back the hyper-v provider image for windows_2019 box ?

Looking at https://app.vagrantup.com/StefanScherer/boxes/windows_2019, the hyper-v box existed in the past with [v2020.02.12](https://app.vagrantup.com/StefanScherer/boxes/windows_2019/versions/2020.02.12), but not anymore with the latest version.

Thanks in advance.

**Comment by StefanScherer** [comment]
Hello 👋 
Thank you for your interest in one of my boxes. Yes I had to stop providing the Hyper-V boxes, because maintaining the CI pipeline was way too much effort for something that I don't personally use. 
I can recommend looking at Gusztav's boxes, eg. https://app.vagrantup.com/gusztavvargadr/boxes/windows-server-2019-standard, he actively runs packer builds for a lot of boxes and many providers. He's doing a fantastic job 🎉

**Comment by hegyre** [comment]
Hello,
Thanks a lot for your answer. That's clear.

Does it mean you also recommend to use Gusztav's boxes for the boxes that you're still maintening ?

I'm also having hard time to know the differences between your boxes and his boxes (for the equivalent boxes that both of you still maintains).

**Comment by StefanScherer** [comment]
Yes, I've tried some of Gusztav's boxes and it worked well for me. Definitely a recommend as they are more up to date.
I was more on the VMware track, but he now also provides these. But both my work and private Mac are now M1 and no Intel ones, so bye bye to VM's 🥲.

**Comment by hegyre** [comment]
Thanks for your reply again.
Knowing that I mainly use hyperV and virtual box as a backup, I'll then do the switch.

However for your last point, I don't fully agree. With latest vagrant >= 2.4.0 we can now specify the box architecture. So you could build for the same box version multiple box artifacts depending on the arch.
Have a look at https://app.vagrantup.com/rockylinux/boxes/9 for an example.
