### ISSUE TITLE
windows_7.json Timeout waiting for SSH

### ISSUE THREAD

**Issue by basictheprogram** [StefanScherer/packer-windows#99]
Have a need to go back to Windows 7 for some testing. Tried making an image with windows_7.json and I'm getting a timeout waiting for ssh.
```
2018/04/27 05:48:12 Detected IP: 192.168.244.131==> vmware-iso: Timeout waiting for SSH.
2018/04/27 05:48:14 ui error: ==> vmware-iso: Timeout waiting for SSH.
2018/04/27 05:48:26 ui error: Build 'vmware-iso' errored: Timeout waiting for SSH.
2018/04/27 05:48:26 machine readable: vmware-iso,error []string{"Timeout waiting for SSH."}
2018/04/27 05:48:26 ui error: --> vmware-iso: Timeout waiting for SSH.
==> Some builds didn't complete successfully and had errors:
--> vmware-iso: Timeout waiting for SSH.
```
I have not used ssh as a communicator in packer. I do find [Reintroduce SSH to Windows boxes?](https://github.com/StefanScherer/packer-windows/issues/84) so it looks like ssh is coming? Upstream uses ssh already?

I do not find a "communicator" for the Windows7 builders. The [docs](https://www.packer.io/docs/templates/communicator.html) hint that ssh is the default?

I'll do some troubleshooting.

**Comment by StefanScherer** [comment]
The upstream packer-windows had to use SSH as previous Packer version only had this communicator.

I had a look at my windows_7.json and it seems I never had updated it to WinRM. The build will hang as the win-updates script calls a:\enable-winrm instead of a:\openssh to open the communicator port.
Either add WinRM communication to the windows_7 template or make the win-updates script more flexible which script is on the floppy drive to run it after all updates.

**Comment by StefanScherer** [comment]
Closing, I don't put effort in Windows 7 images. If someone finds a solution and wants to provide a PR I'm happy to accept it.
